DROP DATABASE IF EXISTS WebSiteVPN;
CREATE DATABASE WebSiteVPN;
USE WebSiteVPN;

/*TABLE ID_USERS*/
CREATE TABLE USERS(
	ID_USER INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	LASTNAME VARCHAR(30) NOT NULL,
	AGE INTEGER,
	EMAIL VARCHAR(30),
	TIMES INTEGER(2),
	PRIMARY KEY(ID_USER)
);

/*TABLE SESSIONS*/
CREATE TABLE SESSIONS(
	ID_SESSION INTEGER NOT NULL AUTO_INCREMENT,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL,
	POINTS INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	PRIMARY KEY(ID_SESSION),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER)
);

/*TABLE QUESTIONS*/
CREATE TABLE QUESTIONS(
	ID_QUESTION INTEGER NOT NULL,
	QUESTION VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_QUESTION)
);

/*TABLE RANDOM QUESTION*/
CREATE TABLE RANDOM_Q(
	ID_SESSION INTEGER NOT NULL,
	ID_QUESTION INTEGER NOT NULL,
	FOREIGN KEY(ID_SESSION) REFERENCES SESSIONS(ID_SESSION),
	FOREIGN KEY(ID_QUESTION) REFERENCES QUESTIONS(ID_QUESTION),
	PRIMARY KEY(ID_SESSION, ID_QUESTION)
);

/*TABLE ANSWERS*/
CREATE TABLE ANSWERS(
	ID_ANSWER INTEGER NOT NULL,
	TEXT_ANSWER VARCHAR(150) NOT NULL,
	CORRECT_ANSWER BOOLEAN NOT NULL,
	ID_QUESTION INTEGER NOT NULL,
	PRIMARY KEY(ID_ANSWER),
	FOREIGN KEY(ID_QUESTION) REFERENCES QUESTIONS(ID_QUESTION)
);

/*HOW MANY TIMES DID THE TEST A USER*/
DELIMITER //
CREATE PROCEDURE TimeUserDoTest()
BEGIN
	SELECT NAME, LASTNAME, TIMES FROM USERS;
END //
DELIMITER ;

/*SEE THE QUESTIONS IN TABLE "QUESTIONS"*/
DELIMITER //
CREATE PROCEDURE SeeQuestion()
BEGIN
	SELECT ID_QUESTION, QUESTION FROM QUESTIONS;
END //
DELIMITER ;

/*SEE THE QUESTIONS IN TABLE "QUESTIONS" WITH ANSWERS*/
DELIMITER //
CREATE PROCEDURE SeeQuestionAnswers()
BEGIN
	SELECT Q.ID_QUESTION, Q.QUESTION, A.TEXT_ANSWER, A.CORRECT_ANSWER FROM QUESTIONS AS Q, ANSWERS AS A WHERE Q.ID_QUESTION=A.ID_QUESTION;
END //
DELIMITER ;



/*TEST DATE */
INSERT INTO USERS VALUES(1, "Adi", "Aioane", 18, "adyxxx5@yahoo.com", 1);
INSERT INTO SESSIONS VALUES(1, "2016/04/17 16:00:32", "2016/04/17 16:40:22", 23, 1);
INSERT INTO QUESTIONS VALUES(1, "Che cosa è l'HOMEWORKING?"),(2, "Che cosa è ");
INSERT INTO ANSWERS VALUES(1,"RISPOSTA A", FALSE, 1),(2,"RISPOSTA B", FALSE, 1), (3,"RISPOSTA C", TRUE, 1), (4,"RISPOSTA A", TRUE, 2);

