DROP DATABASE IF EXISTS WebSiteVPN;
CREATE DATABASE WebSiteVPN;
USE WebSiteVPN;

/*TABLE ID_USERS*/
CREATE TABLE USERS(
	ID_USER INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	LASTNAME VARCHAR(30) NOT NULL,
	AGE DATE,
	EMAIL VARCHAR(30),
	PRIMARY KEY(ID_USER)
);

/*TABLE SESSIONS*/
CREATE TABLE SESSIONS(
	ID_SESSION INTEGER NOT NULL AUTO_INCREMENT,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	POINTS INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	PRIMARY KEY(ID_SESSION),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER)
);

/*TABLE QUESTIONS*/
CREATE TABLE QUESTIONS(
	ID_QUESTION INTEGER NOT NULL,
	QUESTION VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_QUESTION)
);

/*TABLE RANDOM QUESTION*/
CREATE TABLE RANDOM_Q(
	ID_SESSION INTEGER NOT NULL,
	ID_QUESTION INTEGER NOT NULL,
	FOREIGN KEY(ID_SESSION) REFERENCES SESSIONS(ID_SESSION),
	FOREIGN KEY(ID_QUESTION) REFERENCES QUESTIONS(ID_QUESTION),
	PRIMARY KEY(ID_SESSION, ID_QUESTION)
);

/*TABLE ANSWERS*/
CREATE TABLE ANSWERS(
	ID_ANSWER INTEGER NOT NULL,
	TEXT_ANSWER VARCHAR(150) NOT NULL,
	CORRECT_ANSWER BOOLEAN NOT NULL,
	ID_QUESTION INTEGER NOT NULL,
	PRIMARY KEY(ID_ANSWER),
	FOREIGN KEY(ID_QUESTION) REFERENCES QUESTIONS(ID_QUESTION)
);
